[package]
name = "snake-game-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
gl = "0.14.0"
piston = "1.0.0"
piston2d-graphics = "0.45.0"
pistoncore-glutin_window = "0.72.0"
piston2d-opengl_graphics = "0.89.0"
rand = "0.9.1"
nd_array = "0.1.0"